name: Developer Pull Request

on:
  push:
    branches:
      - Developer  # Aciona quando houver um push na branch dev

jobs:
  suggest_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh

      - name: Authenticate with GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GITHUB_TOKEN}" | gh auth login --with-token

      - name: Check for existing pull requests
        id: check_pr
        run: |
          if gh pr list --state open --base main | grep "Developer"; then
            echo "A pull request from Developer to main already exists."
            echo "::set-output name=pr_exists::true"
          else
            echo "::set-output name=pr_exists::false"
          fi

      - name: Create Pull Request
        if: steps.check_pr.outputs.pr_exists == 'false'
        run: |
          gh pr create --base main --head dev --title "Merge changes from dev to main" --body "This PR merges the latest changes from dev into main." --label "auto-merge"

      - name: Comment on existing PR
        if: steps.check_pr.outputs.pr_exists == 'true'
        run: |
          echo "Commenting on existing pull request..."
          pr_number=$(gh pr list --state open --base main --json number --jq '.[0].number')
          gh pr comment $pr_number --body "A new push was made to the dev branch. Please review the changes!"
