name: Merge Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - Developer

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Run Tests
        run: npm test

      - name: Format Code
        run: npm run format

      - name: Merge Dev into Main
        run: |
          echo "Starting merge process..."
          git fetch origin
          git checkout main
          git pull origin main
          if git merge --no-ff origin/Developer; then
            git push origin main
          else
            echo "Merge conflict detected. Please resolve conflicts manually."
            # Adiciona um comentário na PR para notificar sobre o conflito
            gh pr comment ${{ github.event.pull_request.number }} --body "Merge conflict detected while trying to merge into main. Please resolve conflicts before proceeding."
            exit 1
          fi

      - name: Notify on PR
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "New Pull Request opened! @team-name"  # Mencione a equipe aqui

      - name: Notify Success
        if: success()
        run: echo "Merge completed successfully!"
