name: Create Pull Request

on:
  push:
    branches:
      - Developer

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Automated Pull Request'
          body: 'This pull request was created automatically.'
          base: main
          branch: Developer