name: Open Pull Request on Developer Change  

on:  
  push:  
    branches:  
      - Developer  

jobs:  
  create-pull-request:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Check out the code  
        uses: actions/checkout@v2  

      - name: Create Pull Request  
        run: |  
          gh pr create --base main --head developer --title "Automated Pull Request" --body "This PR is created automatically when changes are pushed to the developer branch."  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
