name: Create Pull Request Workflow

on:
  push:
    branches:
      - Developer  # Dispara o workflow sempre que houver um push no branch Developer

permissions:
  contents: write  # Permite escrita no repositório
  pull-requests: write  # Permite criar e gerenciar PRs

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Authenticate gh CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create Pull Request
        run: |
          echo "Creating Pull Request from Developer to Main..."
          gh pr create --base main --head Developer --title "Merge Developer into Main" --body "This PR merges changes from Developer into Main."
