name: Auto PR from Developer Branch

on:
  push:
    branches:
      - Developer

permissions:
  contents: write
  pull-requests: write

jobs:
  open_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Check for changes
        id: changes
        run: |
          git fetch origin main
          git diff --quiet origin/main..HEAD || echo "changes" >> changes.txt
          echo "::set-output name=changes::$(cat changes.txt)"

      - name: Create Pull Request
        if: steps.changes.outputs.changes != ''
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Automated Pull Request'
          body: |
            This pull request is automatically created from the Developer branch.
          base: main
          head: Developer
