name: Push Workflow

on:
  push:
    branches:
      - Developer

permissions:
  contents: write  # Permissões para escrever no conteúdo do repositório
  pull-requests: write  # Permissões para criar e gerenciar pull requests

jobs:
  push_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

      - name: Push Changes (ou outra ação desejada)
        run: |
          # Aqui você pode realizar outras ações que não envolvem o merge
          echo "Realizando outras operações..."
          # Exemplo: git add, git commit ou qualquer outra tarefa que você precise
