name: Auto PR from Developer Branch

on:
  push:
    branches:
      - Developer

jobs:
  open_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Automated Pull Request from Developer'
          body: |
            This pull request is automatically created from the Developer branch.
            
            ## 📝 Revisores
            [@WillDantasJPG](https://github.com/WillDantasJPG) | [@Danielr194](https://github.com/Danielr194)
          base: main  # A branch para a qual a PR será aberta
          head: Developer
          draft: true  # Para garantir que não seja um rascunho
