name: Push Workflow

on:
  push:
    branches:
      - Developer

permissions:
  contents: write
  pull-requests: write

jobs:
  push_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

      - name: Create Pull Request
        run: |
          gh pr create --base main --head Developer --title "Merge Developer into Main" --body "Automated merge from Developer to Main"
