name: Merge and Push Workflow

on:
  push:
    branches:
      - Developer

permissions:
  contents: write  # Permissões para escrever no conteúdo do repositório
  pull-requests: write  # Permissões para criar e gerenciar pull requests

jobs:
  merge_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

      - name: Merge Branch
        run: |
          echo "Merging Developer into Main..."
          git checkout main
          git pull origin main  # Atualiza o branch main
          git merge Developer
          git push origin main  # Faz o push do merge

      - name: Create Pull Request (opcional)
        run: |
          echo "Creating Pull Request from Developer to Main..."
          gh pr create --base main --head Developer --title "Merge Developer into Main" --body "This PR merges changes from Developer into Main."
