name: Push Workflow

on:
  push:
    branches:
      - Developer

permissions:
  contents: write
  pull-requests: write

jobs:
  push_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use seu PAT aqui

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Merge Developer into Main
        run: |
          git checkout main
          git pull origin main
          git merge Developer
          git push origin main
