name: Auto PR from Developer Branch

on:
  push:
    branches:
      - Developer

permissions:
  contents: write
  pull-requests: write

jobs:
  open_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes
        id: changes
        run: |
          # Fetch the main branch
          git fetch origin main
          # Check for changes between the Developer branch and main
          git diff --quiet origin/main...HEAD || echo "changes" >> changes.txt

      - name: Create Pull Request
        if: steps.changes.outputs.changes != ''
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Automated Pull Request'
          body: |
            This pull request is automatically created from the Developer branch.
          base: main
          head: Developer
          # Use this parameter to avoid creating a new branch
          commit-message: "Create pull request from Developer"
